### ISSUE TITLE
Deal, Hit, and Stand Functions

### ISSUE THREAD

**Issue by BlakePerrin13** [BlakePerrin13/CSC-132-Final-Project#5]
In order to have easier control of the game, I think we should work on making functions for the deal, hit, and stand buttons. This would make it way easier to apply the win function as well as automate the dealer to draw cards if a user has busted.

**Comment by BlakePerrin13** [comment]
I am going to be working on this tonight and tomorrow but I just wanted to update y'all on what my plans were.

**Comment by CamJak** [comment]
I did what I believe you're asking but I would check the code and make sure what I did was what you meant, because we already have functions that do the button "operations" but I made functions for the button "checks".
